version: '3'
services:
 redis:
   image: "redis:latest"
 web:
   build: .
   ports:
     - "8080:8080"
   command: bash -c "python manage.py makemigrations main_api && python manage.py migrate && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
   depends_on:
     - redis
   volumes:
     - ./:/diaryDjango
 celery:
   build: .
   command: bash -c "apt-get update && celery -A diary worker -B -l info"

   links:
     - redis
   depends_on:
     - redis
   environment:
     REDIS_URL: "redis://redis:6379"
   volumes:
     - ./:/diaryDjango
